name: boardview
description: Custom item and page re-ordering library for Roblu.
version: 0.1.0
homepage: https://github.com/RobluScouting/FlutterBoardView

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  smooth_page_indicator: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
